2025-05-06 21:26:56,158 - app.main - INFO - BCA Citizen Service starting, logs will be saved to: logs/bca_service_20250506.txt
2025-05-06 21:26:56,163 - app.main - INFO - Citizen Service starting up...
2025-05-06 21:26:56,163 - app.services.kafka_consumer - INFO - Starting Kafka consumer for topic btp_events with bootstrap servers: localhost:29092
2025-05-06 21:26:56,163 - app.services.kafka_consumer - INFO - Using bootstrap servers: ['localhost:29092']
2025-05-06 21:26:56,163 - aiokafka.consumer.subscription_state - INFO - Updating subscribed topics to: frozenset({'btp_events'})
2025-05-06 21:26:56,163 - app.services.kafka_consumer - INFO - Consumer created, attempting to start...
2025-05-06 21:26:56,165 - aiokafka - ERROR - Unable connect to "localhost:29092": [Errno 111] Connection refused
2025-05-06 21:26:56,165 - app.services.kafka_consumer - ERROR - Failed to start Kafka consumer: KafkaConnectionError: Unable to bootstrap from [('localhost', 29092, <AddressFamily.AF_UNSPEC: 0>)]
Traceback (most recent call last):
  File "/home/duyhung/Desktop/DATN/citizen-management-system_v5/service/be/citizen_service_bca/app/services/kafka_consumer.py", line 51, in start
    await self.consumer.start()
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/aiokafka/consumer/consumer.py", line 371, in start
    await self._client.bootstrap()
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/aiokafka/client.py", line 266, in bootstrap
    raise KafkaConnectionError(f"Unable to bootstrap from {self.hosts}")
aiokafka.errors.KafkaConnectionError: KafkaConnectionError: Unable to bootstrap from [('localhost', 29092, <AddressFamily.AF_UNSPEC: 0>)]
2025-05-06 21:26:56,167 - asyncio - ERROR - Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x712178448380>
